FROM braintwister/ubuntu-16.04

LABEL maintainer="Jurgis Pods <pederpansen@users.noreply.github.com>"
LABEL description="Finite element simulations of the intra- and extracellular potential caused by an action potential propagating through an axon fiber. For more information visit https://github.com/pederpansen/dune-ax1"

RUN apt-add-repository -y ppa:ubuntu-toolchain-r/test \
 && apt-get update \
 && apt-get install -y --no-install-recommends \
    gcc-4.7 \
    g++-4.7 \
    gdb \
    linux-tools-generic \
    clang \
    patch \
    pkg-config \
    autotools-dev \
    autoconf \
    libtool \
    m4 \
    automake \
    gfortran \
    libblas-dev \
    liblapack-dev \
    csh \
    zlib1g-dev \
    less \
    nano \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/* \
 && ln -sf /usr/bin/g++-4.7 /usr/bin/g++ \
 && ln -sf /usr/bin/gcc-4.7 /usr/bin/gcc

ENV CC gcc
ENV CXX g++

# Install OpenMPI
ENV OPENMPI_VERSION 1.8.8
RUN wget https://download.open-mpi.org/release/open-mpi/v1.8/openmpi-${OPENMPI_VERSION}.tar.gz \
  && gunzip -c openmpi-${OPENMPI_VERSION}.tar.gz | tar xf - \
  && cd openmpi-${OPENMPI_VERSION} \
  && ./configure --prefix=/usr/local \
  && make all install \
  && cd .. \
  && rm -rf openmpi-${OPENMPI_VERSION}*
ENV LD_LIBRARY_PATH /usr/local/lib

# Install parallel HDF5
RUN wget https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.1/src/hdf5-1.8.1.tar.gz \
  && gunzip -c hdf5-1.8.1.tar.gz | tar xf - \
  && cd hdf5-1.8.1 \
  && CC=clang ./configure --enable-parallel --prefix=/usr/local \
  && make \
  && make install \
  && cd .. \
  && rm -rf hdf5-1.8.1*
  
RUN mkdir /dune
WORKDIR /dune

# Install SuperLU
ADD docker-deps/superlu-make.linux /dune/superlu-make.linux
RUN cd /dune \
  && wget https://crd-legacy.lbl.gov/~xiaoye/SuperLU/superlu_4.3.tar.gz \
  && gunzip -c superlu_4.3.tar.gz | tar xf - \
  && cd SuperLU_4.3 \
  && mv /dune/superlu-make.linux make.inc \
  && cat make.inc \
  && make blaslib \  
  && make \
  && cd .. \
  && rm -rf superlu_4.3.tar.gz

RUN git clone https://github.com/dune-project/dune-common.git
RUN cd dune-common && git checkout 5b0bdc28589f4d66b8b56c6a4d781cf19f10774f && cd ..
RUN git clone https://github.com/dune-project/dune-geometry.git
RUN cd dune-geometry && git checkout 3dafcc20186428e9669a90d69eae3bcc8b08d9a1 && cd ..
RUN git clone https://github.com/dune-project/dune-grid.git
RUN cd dune-grid  && git checkout 12091a82828433ab050c70c0a87e643197993f97 && cd ..
RUN git clone https://github.com/dune-project/dune-istl.git
RUN cd dune-istl && git checkout 35b879c3f0d003dcbe743c7ca84f6142751c6b48 && cd ..
RUN git clone https://github.com/dune-project/dune-localfunctions.git
RUN cd dune-localfunctions && git checkout 25a1116ad55bc183ecd5d66232564c85c22cb455 && cd ..
RUN git clone https://github.com/dune-project/dune-typetree.git
RUN cd dune-typetree && git checkout  6730ea7fd6c44b6206555e664be071c40dc10b48 && cd ..
RUN git clone https://github.com/dune-project/dune-pdelab.git
RUN cd dune-pdelab && git checkout  9f4d7a979c5369cfe2232d77e034253202f69a8b && cd ..
RUN git clone https://github.com/smuething/dune-multidomaingrid.git
RUN cd dune-multidomaingrid && git checkout 406c5c750650ebaf1b5811e9fb6012899b238064 && cd ..
RUN git clone https://github.com/smuething/dune-multidomain.git
RUN cd dune-multidomain && git checkout 2aa14eeb57d3f94563b926c637ebfe9235112c9d && cd ..
ADD stuff/ax1_docker.opts /dune/ax1.opts
RUN dune-common/bin/dunecontrol --no-cmake --module=dune-multidomain --opts=ax1.opts all

ADD . /dune/dune-ax1
RUN cd dune-pdelab && patch -p1 < ../dune-ax1/stuff/pdelab_ax1.patch && cd ..

RUN dune-common/bin/dunecontrol --no-cmake --only=dune-ax1 --opts=ax1.opts all || true
RUN rm dune-ax1/src/acme2_2d-acme2_cyl_par.o || true
RUN ls -al dune-ax1/src/acme2_cyl_par
RUN ls -al dune-ax1/src/acme2_cyl_par_myelin

RUN mkdir -p /dune/output
RUN mkdir -p /dune/simulation_states

ADD bin/run.sh /dune 

ENTRYPOINT ["/dune/run.sh"]