#!/bin/bash

np=$1

configfile=$2
logfile=`echo $configfile | sed -e 's/config/log/g'`
logfile=`echo $logfile | sed -e "s/.log/_p${np}.log/g"`

rankfile=$3

if [ $# -lt 4 ]
then
  tend=50
else
  tend=$4
fi

echo "Using config file: $configfile"
echo "Using log file: $logfile"
echo "Starting simulation using $np processes until tend=${tend}!"

sh -c "( (nohup mpirun -rf $rankfile -report-bindings -np $np ./acme2_cyl_par 0 1 $tend $configfile 2>&1 >$logfile </dev/null) & )"
