#!/bin/bash

np=$1

configfile=$2
logfile=`echo $configfile | sed -e 's/config/log/g'`
logfile=`echo $logfile | sed -e "s/.log/_p${np}.log/g"`
#logfile=/dev/null
level=0
dt=1
tend=20e3

echo "Using config file: $configfile"
echo "Using log file: $logfile"
echo "Starting simulation using $np processes!"

sh -c "( (nohup mpirun -bind-to-core -bysocket -report-bindings -np $np ./acme2_cyl_par $level $dt $tend $configfile 2>&1 >$logfile </dev/null) & )"
